name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Kontore.Dithering
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: Dithering/Dithering.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Kontore.Dithering.FireBitmap
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: Dithering/Dithering.FireBitmap.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
