name: Tests

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload DLLs artifact
      uses: actions/upload-artifact@v2
      with:
        name: DLLs
        path: "**/bin/Release/**/"
        
  Test:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Projects artifact
      uses: actions/download-artifact@v2
      with:
        name: DLLs
    - name: Test
      run: dotnet test "**/*Tests.dll" --no-build --verbosity normal --configuration Release